version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-server
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${PSQ_USER}
      POSTGRES_PASSWORD: ${PSQ_PASS}
      POSTGRES_DB: ${PSQ_NAME}
    ports:
      - "${PSQ_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: blog-backend
    depends_on:
      - postgres
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${PSQ_NAME}
      SPRING_DATASOURCE_USERNAME: ${PSQ_USER}
      SPRING_DATASOURCE_PASSWORD: ${PSQ_PASS}
      SERVER_PORT: ${BACKEND_PORT:-8080}
    ports:
      - "${BACKEND_PORT:-8080}:8080"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: blog-frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-4200}:80"

volumes:
  postgres_data:
