FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

COPY backend/blog/pom.xml .
RUN mvn dependency:go-offline

COPY backend/blog/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

COPY --from=build /app/target/blog-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
